import React from 'react'


export const metadata = {
    title: "Contact page",
    description: "Generated by create next app",
};

export default function layout({ children }) {
    return (
        <div className='bg-blue-500'>
            {children}
        </div>
    )
}
